name: "Terraform Apply"

on:
  pull_request:
    types:
      - closed
    branches:
      - master
    head_ref:
      - feature/** 

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: "ubuntu-latest"
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Terraform init"
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
  